language: php
script: php --version
deploy:
- provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_KEY
  bucket: srm-web-fe-build-artifcat
  skip_cleanup: true
env:
  global:
  - secure: g++6SghJ4mvQm9kubwAuI3dBQe4Ps3IKfan9cbmQrdYjBXjaf0AS8JiFj/oIPoSqpCIik5WuXbe2tTWNSBsEwcXexw2u7UjjnDmAg7prTonwT8O2HKfx00T4qeUHU1Y+UidQemOu/y2faDRPwdNihD63YkxIftP49MA8E07q3nU=
  - secure: j61jGlvk6CQetn9nNLaa5Y3BgvQH/jArZ2O4WLp68qqA1YWPKz89gFyysFUixj0UrKn2DFh6j7sdbwU6h0OUoQ2KuMbWXgbn/k3B2y8Rgy3WkLbrDm5aD6sJKWoWqpcGrEkjGe1oZXRnksZEW/YmGpRv1Af6ZBDABbSA1+twiJw=
  - REGION=us-east-1
  - ELB_ENV_ID=e-9wv2dgkbhv
  - APPLICATION_NAME="Simple Recipe Manager"
  - BUCKET_NAME=srm-web-fe-build-artifcat
  - FILE_KEY=Dockerfile
after_deploy:
- sudo pip install awscli
- export AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID
- export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
- export AWS_DEFAULT_REGION=$REGION
- export VERSION=$(git rev-parse --short HEAD)
- aws elasticbeanstalk create-application-version --application-name "$APPLICATION_NAME" --version-label $VERSION --source-bundle S3Bucket=$BUCKET_NAME,S3Key=$FILE_KEY
- aws elasticbeanstalk update-environment --environment-id $ELB_ENV_ID --version-label $VERSION