language: java
jdk:
  - oraclejdk8
deploy:
- provider: s3
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key: "$SECRET_KEY"
  bucket: $BUCKET_NAME
  skip_cleanup: true
  upload-dir: $FOLDER
  on:
    all_branches: true
env:
  global:
  - REGION=us-east-1
  - ELB_ENV_ID=$(cat envId)
  - APPLICATION_NAME="Simple Recipe Manager"
  - BUCKET_NAME=travis-build-artifacts
  - FOLDER=travis-srm-web-fe
  - FILE_KEY=$FOLDER/Dockerfile
  - secure: "ONMlGWT4jGech3tpMJxCX8ZA1pE+e9uh7Ton9ek3TGZzL5Cmn/QMW/PtEJQDOrDNW7+LuR63SxxKXm2c0JXMnfRLEoQnQywVZzn4B4U9dfdKgLcnv/Npgl0Jr6RKB2JUao/66PzjwZrKvIVJnanG/pTiBUaZxn5k8QgA3knh6rc="
  - secure: "bbG1HJ5I6bCk4v3ghfIklcttqkZdv97n4AfdjT82kc8DtFQc6WXYFhAixImD5CjPy19Zg6gi1MeJfX8i6lHzQYezwyQ0iYUIOkkuc1KvBDgtmkRjZeB/CWHkmULcbQtiku3LMyP1wal+FEQ4N4ltYNRo7kxgAFllstKc2RB8Dt8="
after_deploy:
- sudo pip install awscli
- export AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID
- export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
- export AWS_DEFAULT_REGION=$REGION
- export VERSION=$(git rev-parse --short HEAD)
- git fetch --all
- export BRANCH=$TRAVIS_BRANCH
- export VERSION_LABEL="$BRANCH-$VERSION"
- aws elasticbeanstalk create-application-version --application-name "$APPLICATION_NAME" --version-label "$VERSION_LABEL" --source-bundle S3Bucket=$BUCKET_NAME,S3Key=$FILE_KEY
- aws elasticbeanstalk update-environment --environment-id $ELB_ENV_ID --version-label $VERSION_LABEL
