FROM kyma/docker-nginx

# Install unzip
RUN apt-get install -y unzip
# Install curl
RUN apt-get install -y curl

RUN curl -L https://s3.amazonaws.com/travis-build-artifacts/travis-srm-web-fe/build/JAR_NAME.zip -o /tmp/deploy.zip

RUN unzip -uo /tmp/deploy.zip -d /var/www/

ADD  /var/www
CMD 'nginx'
