FROM kyma/docker-nginx
ADD https://raw.github.com/h5bp/server-configs-nginx/master/h5bp/directive-only/cross-domain-insecure.conf /etc/nginx/h5bp/directive-only/cross-domain-insecure.conf
RUN apt-get update
RUN apt-get install -y unzip wget

RUN wget --no-check-certificate -O /tmp/deploy.zip https://s3.amazonaws.com/travis-build-artifacts/travis-srm-web-fe/build/JAR_NAME.zip

RUN unzip -uo /tmp/deploy.zip -d /var/www/

CMD 'nginx'

EXPOSE 80